name: test_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  geolocator: ^10.0.0
  url_launcher: ^6.1.9
  http: ^1.0.0
  font_awesome_flutter: ^10.1.0
  sensors_plus: ^2.0.0
  flutter_compass: ^0.8.0
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.0.0 
  flutter_rating_bar: ^4.0.0
  google_fonts: ^2.3.2
  gradient_borders: ^1.0.0
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  http: ^1.0.0
